{{
    config(
        materialized = 'view',
        database = var('tgt_db'),
        schema = var('tgt_sch'),
        alias = 'VW_CUSTOMER_DATA'
    )
}}

SELECT
    CUST.CUSTOMERID,
    CUST.CUSTOMERNAME,
    CUST.SEGMENT,
    CUST.STATE,
    CUST.COUNTRY,
    ORD.ORDERDATE,
    ORD.SHIPDATE,
    ORD.SHIPMODE,
    ORD.ORDERCOSTPRICE,
    ORD.ORDERSELLINGPRICE,
    PRODUCT.PRODUCT_NAME,
    PRODUCT.CATEGORY
FROM 
RAW_DB.GLOBALMART.CUSTOMER AS CUST
INNER JOIN RAW_DB.GLOBALMART.ORDERS AS ORD ON CUST.CUSTOMERID = ORD.CUSTOMERID
INNER JOIN RAW_DB.GLOBALMART.PRODUCTS AS PRODUCT ON ORD.PRODUCTID = PRODUCT.PRODUCT_ID